a=float(input("enter a number:"))
b=float(input("enter a number:"))
print("addition:",a+b)
print("subtract:",a-b)
print("multiply:",a*b)
print("integer division:",a/b)
print("floor division:",a//b)
print("modulo division:",a%b)
